version: '3.11'

services:
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    tty: true
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/habits_app
    restart: always

  celery:
    build: .
    depends_on:
      web:
        condition: service_started
    tty: true
    command: celery -A config worker -l INFO
    volumes:
      - .:/habits_app


  celery-beat:
      build: .
      depends_on:
        web:
          condition: service_started
        db:
          condition: service_healthy
      tty: true
      command: python manage.py migrate && celery -A config beat -l INFO
      volumes:
        - .:/habits_app

volumes:
    pg_data:
